name: "Terraform Cloud Deploy"

on:
  push:
    branches:
      - main

env:
  CONFIG_DIRECTORY: "lab-7"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.CONFIG_DIRECTORY }}