name: "Terraform Cloud Deploy"

on:
  push:
    branches:
      - main
    
      

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_API_URL: "app.terraform.io"
  CONFIG_DIRECTORY: "lab-7"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.7  # Modifiez en fonction de la version souhaitée

      - name: Configure Terraform Cloud
        run: |
          ls -a
          echo "credentials \"$TF_API_URL\" {" >> ~/.terraformrc
          echo "  token = \"${{ secrets.TF_API_TOKEN }}\"" >> ~/.terraformrc
          echo "}" >> ~/.terraformrc
        working-directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Initialize Terraform
        run: |
          terraform init
          ls -a
        working-directory: ${{ env.CONFIG_DIRECTORY }}

        
      - name: Terraform apply
        run: |
          ls -a
          terraform apply --auto-approve
        working-directory: ${{ env.CONFIG_DIRECTORY }}